version: '3'
services:
    app:
        stdin_open: true
        image: 9b9d25d8a54b
    web:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "8080:3000"
        volumes: 
                - /app/node_modules
                - .:/app